#!/bin/bash

NEW_PATH="."
DL_FOLDER="$HOME/Downloads"

while getopts ":m:r:c:d:" opt; do
    case $opt in
	d)
	    echo "Setting downloads folder to $OPTARG"
	    
	m)
	    echo "Moving file $OPTARG from Downloads to $NEW_PATH"
	    mv "$DL_FOLDER/$OPTARG" "$NEW_PATH"
	    NEW_PATH="."
	    ;;
	c)
	    echo "Copying file $OPTARG from Downloads to $NEW_PATH"
	    cp "$DL_FOLDER/$OPTARG" "$NEW_PATH"
	    NEW_PATH="."
	    ;;
	r)
	    echo "Renaming to $OPTARG"
	    NEW_PATH="./$OPTARG"
	    ;;
	\?)
	    echo "Invalid option: -$OPTARG" >&2
	    exit 1
	    ;;
	:)
	    echo "Option -$OPTARG requires an argument." >&2
	    exit 1
	    ;;
    esac
done


