#!/bin/bash

function show_spinner()
{
    local -r pid="${1}"
    local -r delay='0.75'
    local spinstr='\|/-'
    local temp
    while (( `ps -p "${pid}" | wc -l` > 1 ))
    do
	temp="${spinstr#?}"
	printf " [%c]  " "${spinstr}"
	spinstr=${temp}${spinstr%"${temp}"}
	sleep "${delay}"
	printf "\b\b\b\b\b\b"
    done
    printf "     \b\b\b\b\b"
    }

("$@") &
PID=$!
show_spinner $PID




